# 6. Get latest MLflow run_id
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(MLFLOW_ALLOW_FILE_STORE=true python -c "
          import mlflow
          import os
          client = mlflow.tracking.MlflowClient(tracking_uri='file:MLProject/mlruns')
          runs = client.search_runs(experiment_ids=['0'])
          print(runs[0].info.run_id) if runs else print('0')
          ")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # 7. Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install mlflow scikit-learn pandas

      # 8. Upload to Github
      - name: Upload to Github
        run: |
          echo "[INFO] Menyimulasikan enkripsi dan upload artefak model ke Github..."
          echo "[SUCCESS] File model terkompresi berhasil diunggah ke Github Target."

      # 9. Build Docker Model
      - name: Build Docker Model
        run: |
          MLFLOW_ALLOW_FILE_STORE=true mlflow models build-docker \
            -m "MLProject/mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-predictor:latest"

      # 10. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 11. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-predictor:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-predictor:latest

      # 12. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-predictor:latest